import { APP_NOSTR_SIZE } from '@/consts'

const SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: 150,
  [APP_NOSTR_SIZE.LARGE]: 100,
  [APP_NOSTR_SIZE.MEDIUM]: 80,
  [APP_NOSTR_SIZE.SMALL]: 60,
  [APP_NOSTR_SIZE.EXTRA_SMALL]: 50
}

const FONT_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: 42,
  [APP_NOSTR_SIZE.LARGE]: 36,
  [APP_NOSTR_SIZE.MEDIUM]: 24,
  [APP_NOSTR_SIZE.SMALL]: 24,
  [APP_NOSTR_SIZE.EXTRA_SMALL]: 10
}

export const APP_NAME_FONT_SIZE_VALUE = {
  [APP_NOSTR_SIZE.LARGE]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.LARGE],
  [APP_NOSTR_SIZE.BIG]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.BIG],
  [APP_NOSTR_SIZE.MEDIUM]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM],
  [APP_NOSTR_SIZE.SMALL]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.SMALL],
  [APP_NOSTR_SIZE.EXTRA_SMALL]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL]
}

export const APP_NOSTRO_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: {
    height: SIZE_VALUE[APP_NOSTR_SIZE.BIG],
    minWidth: SIZE_VALUE[APP_NOSTR_SIZE.BIG],
    maxWidth: SIZE_VALUE[APP_NOSTR_SIZE.BIG]
  },
  [APP_NOSTR_SIZE.LARGE]: {
    height: SIZE_VALUE[APP_NOSTR_SIZE.LARGE],
    minWidth: SIZE_VALUE[APP_NOSTR_SIZE.LARGE],
    maxWidth: SIZE_VALUE[APP_NOSTR_SIZE.LARGE]
  },
  [APP_NOSTR_SIZE.MEDIUM]: {
    height: SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM],
    minWidth: SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM],
    maxWidth: SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM]
  },
  [APP_NOSTR_SIZE.SMALL]: {
    height: SIZE_VALUE[APP_NOSTR_SIZE.SMALL],
    minWidth: SIZE_VALUE[APP_NOSTR_SIZE.SMALL],
    maxWidth: SIZE_VALUE[APP_NOSTR_SIZE.SMALL]
  },
  [APP_NOSTR_SIZE.EXTRA_SMALL]: {
    height: SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL],
    minWidth: SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL],
    maxWidth: SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL]
  }
}
