import { APP_NOSTR_SIZE } from '@/consts'

const AVATAR_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: 72,
  [APP_NOSTR_SIZE.LARGE]: 50,
  [APP_NOSTR_SIZE.MEDIUM]: 32,
  [APP_NOSTR_SIZE.SMALL]: 24,
  [APP_NOSTR_SIZE.EXTRA_SMALL]: 16
}

export const SKELETON_AVATAR_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: AVATAR_SIZE_VALUE[APP_NOSTR_SIZE.BIG],
  [APP_NOSTR_SIZE.LARGE]: AVATAR_SIZE_VALUE[APP_NOSTR_SIZE.LARGE],
  [APP_NOSTR_SIZE.MEDIUM]: AVATAR_SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM],
  [APP_NOSTR_SIZE.SMALL]: AVATAR_SIZE_VALUE[APP_NOSTR_SIZE.SMALL],
  [APP_NOSTR_SIZE.EXTRA_SMALL]: AVATAR_SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL]
}
