import { APP_NOSTR_SIZE } from '@/consts'

const FONT_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: 24,
  [APP_NOSTR_SIZE.LARGE]: 16,
  [APP_NOSTR_SIZE.MEDIUM]: 14,
  [APP_NOSTR_SIZE.SMALL]: 12,
  [APP_NOSTR_SIZE.EXTRA_SMALL]: 10
}

export const SKELETON_TEXT_FONT_SIZE_VALUE = {
  [APP_NOSTR_SIZE.BIG]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.BIG],
  [APP_NOSTR_SIZE.LARGE]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.LARGE],
  [APP_NOSTR_SIZE.MEDIUM]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.MEDIUM],
  [APP_NOSTR_SIZE.SMALL]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.SMALL],
  [APP_NOSTR_SIZE.EXTRA_SMALL]: FONT_SIZE_VALUE[APP_NOSTR_SIZE.EXTRA_SMALL]
}
