import { APP_NOSTRO_SIZE } from '@/consts'

const FONT_SIZE_VALUE = {
  [APP_NOSTRO_SIZE.LARGE]: 16,
  [APP_NOSTRO_SIZE.MEDIUM]: 14,
  [APP_NOSTRO_SIZE.SMALL]: 10,
  [APP_NOSTRO_SIZE.EXTRA_SMALL]: 10
}

const NAME_GUTTER_VALUE = {
  [APP_NOSTRO_SIZE.LARGE]: '6px',
  [APP_NOSTRO_SIZE.MEDIUM]: '4px',
  [APP_NOSTRO_SIZE.SMALL]: '2px',
  [APP_NOSTRO_SIZE.EXTRA_SMALL]: '2px'
}

export const APP_NAME_FONT_SIZE_VALUE = {
  [APP_NOSTRO_SIZE.LARGE]: FONT_SIZE_VALUE[APP_NOSTRO_SIZE.LARGE],
  [APP_NOSTRO_SIZE.MEDIUM]: FONT_SIZE_VALUE[APP_NOSTRO_SIZE.MEDIUM],
  [APP_NOSTRO_SIZE.SMALL]: FONT_SIZE_VALUE[APP_NOSTRO_SIZE.SMALL],
  [APP_NOSTRO_SIZE.EXTRA_SMALL]: FONT_SIZE_VALUE[APP_NOSTRO_SIZE.EXTRA_SMALL]
}

export const APP_NAME_GUTTER_VALUE = {
  [APP_NOSTRO_SIZE.LARGE]: NAME_GUTTER_VALUE[APP_NOSTRO_SIZE.LARGE],
  [APP_NOSTRO_SIZE.MEDIUM]: NAME_GUTTER_VALUE[APP_NOSTRO_SIZE.MEDIUM],
  [APP_NOSTRO_SIZE.SMALL]: NAME_GUTTER_VALUE[APP_NOSTRO_SIZE.SMALL],
  [APP_NOSTRO_SIZE.EXTRA_SMALL]: NAME_GUTTER_VALUE[APP_NOSTRO_SIZE.EXTRA_SMALL]
}
